services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: developer_blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      TZ: Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
