import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomUUID } from 'node:crypto';
import { mkdtemp, readdir, readFile, unlink, rmdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { Client } from 'pg';
import { encode } from '@auth/core/jwt';
import sharp from 'sharp';
import dotenv from 'dotenv';
dotenv.config({ quiet: true });

const prefix = 'DB_RICH_TEXT_V1:';
const content = (url, text = 'Integration post') => prefix + JSON.stringify({ type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text }] }, ...(url ? [{ type: 'image', attrs: { src: url, alt: 'test' } }] : [])] });

test('post, draft, permission, category and image lifecycle', { timeout: 120000 }, async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'developer-blog-lifecycle-'));
  const admin = new Client({ connectionString: process.env.DATABASE_URL });
  await admin.connect();
  const databaseName = 'developer_blog_test_' + randomUUID().replaceAll('-', '');
  assert.match(databaseName, /^developer_blog_test_[a-f0-9]{32}$/);
  await admin.query('CREATE DATABASE "' + databaseName + '"');
  const databaseUrl = new URL(process.env.DATABASE_URL);
  databaseUrl.pathname = '/' + databaseName;
  const db = new Client({ connectionString: databaseUrl.toString() });
  try {
    await db.connect();
    for (const migration of (await readdir('prisma/migrations')).sort()) {
      if (!/^\d/.test(migration)) continue;
      await db.query(await readFile(path.join('prisma/migrations', migration, 'migration.sql'), 'utf8'));
    }
  } catch (error) {
    await db.end();
    await admin.query('DROP DATABASE "' + databaseName + '" WITH (FORCE)');
    await admin.end();
    await rmdir(directory);
    throw error;
  }
  const owner = randomUUID(), other = randomUUID(), friend = randomUUID();
  const catA = randomUUID(), catB = randomUUID(), divider = randomUUID();
  const secret = randomUUID();
  const authSecret = randomUUID();
  const base = 'http://localhost:3114';
  let log = '';
  const server = spawn(process.execPath, ['node_modules/next/dist/bin/next', 'start', '--port', '3114'], { cwd: process.cwd(), windowsHide: true, env: { ...process.env, DATABASE_URL: databaseUrl.toString(), AUTH_SECRET: authSecret, AUTH_URL: base, AUTH_TRUST_HOST: 'true', UPLOAD_DIR: directory, CRON_SECRET: secret }, stdio: ['ignore', 'pipe', 'pipe'] });
  server.stdout.on('data', data => { log += data; }); server.stderr.on('data', data => { log += data; });
  try {
    for (const [id, name] of [[owner, 'LifecycleAuthor'], [other, 'LifecycleOther'], [friend, 'LifecycleFriend']]) await db.query('INSERT INTO "User" (id,name,"updatedAt") VALUES ($1,$2,NOW())', [id, name]);
    await db.query('UPDATE "User" SET image=$1 WHERE id=$2',['https://example.com/lifecycle-avatar.png',owner]);
    await db.query('INSERT INTO "Friendship" (id,"userId","friendId",status) VALUES ($1,$2,$3,\'ACCEPTED\')', [randomUUID(), owner, friend]);
    for (const [id, name, order, isDivider] of [[catA, 'First category', 0, false], [divider, '--', 1, true], [catB, 'Second category', 2, false]]) await db.query('INSERT INTO "Category" (id,name,"order","isDivider","userId","updatedAt") VALUES ($1,$2,$3,$4,$5,NOW())', [id,name,order,isDivider,owner]);
    let ready = false;
    for (let i=0;i<80;i++) { try { if ((await fetch(base+'/login')).status===200) {ready=true;break;} } catch {} await new Promise(resolve=>setTimeout(resolve,200)); }
    assert.ok(ready,'Server failed to start: '+log);
    const cookie = async id => 'authjs.session-token=' + await encode({ token: { id, sub:id, name:'LifecycleUser' }, secret:authSecret, salt:'authjs.session-token', maxAge:3600 });
    const ownerCookie=await cookie(owner), otherCookie=await cookie(other), friendCookie=await cookie(friend);
    const call = async (url, method='GET', body, session=ownerCookie) => {
      const response=await fetch(base+url,{method,headers:{...(session?{cookie:session}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
      return {status:response.status,body:await response.json().catch(()=>null)};
    };
    // Requests are private, directional, idempotent, and require recipient action.
    assert.equal((await call('/api/notifications','GET',undefined,null)).status,401);
    assert.equal((await call('/api/friends/'+owner,'POST',{},null)).status,401);
    assert.equal((await call('/api/friends/'+owner,'POST',{})).status,400);
    const sent = await call('/api/friends/'+owner,'POST',{},otherCookie);
    assert.equal(sent.status,200,JSON.stringify(sent));
    const requestId = sent.body.friendship.id;
    const crossed = await Promise.all([
      call('/api/friends/'+owner,'POST',{},otherCookie),
      call('/api/friends/'+other,'POST',{},ownerCookie),
    ]);
    for (const result of crossed) assert.equal(result.body.friendship.id,requestId);
    assert.equal((await call('/api/notifications')).body.requests.length,1);
    assert.equal((await call('/api/notifications','GET',undefined,otherCookie)).body.requests.length,0);
    assert.equal((await call('/api/friend-requests/'+requestId,'PATCH',{action:'accept'},otherCookie)).status,404);
    await call('/api/notifications','DELETE',{all:true});
    await call('/api/notifications','DELETE',{id:requestId});
    assert.equal((await call('/api/notifications')).body.requests.length,1,'deletion preserves requests');
    assert.equal((await call('/api/friend-requests/'+requestId,'PATCH',{action:'reject'})).status,200);
    assert.equal((await call('/api/notifications')).body.requests.length,0);
    const nextRequest = await call('/api/friends/'+owner,'POST',{},otherCookie);
    assert.equal((await call('/api/friend-requests/'+nextRequest.body.friendship.id,'PATCH',{action:'accept'})).status,200);
    assert.equal((await call('/api/friends/'+owner,'POST',{},otherCookie)).body.friendship.status,'ACCEPTED');
    const friendPage = await (await fetch(base+'/mypage?tab=friends',{headers:{cookie:ownerCookie}})).text();
    assert.ok(friendPage.includes('LifecycleOther'),'friend management lists accepted friends');
    assert.equal((await call('/api/friends/'+owner,'DELETE',{},null)).status,401);
    await call('/api/friends/'+other,'DELETE',{},friendCookie);
    assert.equal((await db.query('SELECT id FROM "Friendship" WHERE id=$1',[nextRequest.body.friendship.id])).rowCount,1,'third party cannot remove a relationship');
    assert.equal((await call('/api/friends/'+other,'DELETE',{})).status,200);
    assert.equal((await db.query('SELECT id FROM "Friendship" WHERE id=$1',[nextRequest.body.friendship.id])).rowCount,0,'recipient can remove an accepted friendship');
    const pendingAgain = await call('/api/friends/'+owner,'POST',{},otherCookie);
    await call('/api/friends/'+other,'DELETE',{});
    assert.equal((await call('/api/notifications')).body.requests.length,1,'friend removal leaves pending requests untouched');
    await call('/api/friend-requests/'+pendingAgain.body.friendship.id,'PATCH',{action:'reject'});

    const bytes=await sharp({create:{width:32,height:24,channels:3,background:'#446699'}}).png().toBuffer();
    const upload=async()=>{ const form=new FormData();form.append('file',new File([bytes],'test.png',{type:'image/png'}));const r=await fetch(base+'/api/images',{method:'POST',headers:{cookie:ownerCookie},body:form});assert.equal(r.status,201,await r.clone().text());return (await r.json()).url; };
    const image=await upload();
    const name=image.split('/').at(-1);
    assert.equal((await fetch(base+image)).status,404,'unpublished image private');
    assert.equal((await fetch(base+image,{headers:{cookie:ownerCookie}})).status,200);
    let draft=await call('/api/drafts','PUT',{key:'new',title:'Draft title',content:content(image),categoryId:catA,visibility:'PRIVATE',version:null});
    assert.equal(draft.status,200,JSON.stringify(draft));
    let version=draft.body.draft.version;
    assert.equal((await call('/api/drafts?key=new')).body.draft.title,'Draft title');
    assert.equal((await call('/api/drafts?key=new','GET',undefined,otherCookie)).body.draft,null);
    assert.equal((await call('/api/drafts','PUT',{key:'new',title:'Stale',content:content(image),categoryId:catA,visibility:'PRIVATE',version:null})).status,409);
    // A live draft protects an image even if its orphan timestamp is stale.
    await db.query('UPDATE "ImageAsset" SET "orphanedAt"=NOW()-INTERVAL \'2 days\' WHERE name=$1',[name]);
    const cleanup=async()=>{const r=await fetch(base+'/api/maintenance/images',{method:'POST',headers:{authorization:'Bearer '+secret}});assert.equal(r.status,200,await r.clone().text());return r.json();};
    await cleanup();
    assert.equal((await fetch(base+image,{headers:{cookie:ownerCookie}})).status,200);
    const published=await call('/api/posts','POST',{title:'Private lifecycle post',content:content(image),categoryId:catA,visibility:'PRIVATE',draftVersion:version});
    assert.equal(published.status,201,JSON.stringify(published));
    let post=published.body.post;
    assert.equal((await call('/api/drafts?key=new')).body.draft,null);
    assert.equal((await fetch(base+'/posts/'+post.id)).status,404);
    assert.equal((await fetch(base+'/posts/'+post.id,{headers:{cookie:ownerCookie}})).status,200);
    assert.equal((await fetch(base+'/posts/'+post.id+'/edit',{headers:{cookie:otherCookie}})).status,404);
    assert.equal((await call('/api/posts/'+post.id,'PATCH',{title:'Tampered'},otherCookie)).status,404);
    let edited=await call('/api/posts/'+post.id,'PATCH',{title:'Friends lifecycle post',content:content(image),categoryId:catB,visibility:'FRIENDS',updatedAt:post.updatedAt});
    assert.equal(edited.status,200,JSON.stringify(edited));post=edited.body.post;
    assert.equal((await fetch(base+'/posts/'+post.id,{headers:{cookie:friendCookie}})).status,200);
    assert.equal((await fetch(base+image,{headers:{cookie:friendCookie}})).status,200);
    assert.equal((await fetch(base+image,{headers:{cookie:otherCookie}})).status,404);
    edited=await call('/api/posts/'+post.id,'PATCH',{title:'Public lifecycle post',content:content(image),categoryId:catB,visibility:'PUBLIC',updatedAt:post.updatedAt});
    assert.equal(edited.status,200);post=edited.body.post;
    assert.equal((await fetch(base+'/posts/'+post.id)).status,200);
    assert.equal((await fetch(base+image)).status,200);
    const blog=await (await fetch(base+'/blog/'+owner+'?category='+catB)).text();
    assert.ok(blog.includes('Public lifecycle post'));
    assert.ok(blog.indexOf('First category')<blog.indexOf('Second category'),'category order retained');
    assert.ok(blog.includes('https://example.com/lifecycle-avatar.png'),'author photo reaches blog');
    const mypage=await (await fetch(base+'/mypage?tab=posts',{headers:{cookie:ownerCookie}})).text();
    assert.ok(mypage.includes('Public lifecycle post'));
    assert.equal((await call('/api/posts','POST',{title:'Reuse',content:content(image),categoryId:null,visibility:'PUBLIC'},otherCookie)).status,400);
    const shared=await call('/api/posts','POST',{title:'Shared image',content:content(image),categoryId:catA,visibility:'PRIVATE'});
    assert.equal(shared.status,201);
    const outlineContent=prefix+JSON.stringify({type:'doc',attrs:{toc:'shown',tocDepth:3},content:[{type:'heading',attrs:{level:2},content:[{type:'text',text:'First heading'}]},{type:'heading',attrs:{level:3},content:[{type:'text',text:'First heading'}]},{type:'heading',attrs:{level:4},content:[{type:'text',text:'Detailed heading'}]}]});
    const outlinePost=await call('/api/posts','POST',{title:'Outline test',content:outlineContent,categoryId:catB,visibility:'PUBLIC'});
    assert.equal(outlinePost.status,201);
    const outlineId=outlinePost.body.post.id;
    const detail=await (await fetch(base+'/posts/'+outlineId)).text();
    assert.ok(detail.includes('https://example.com/lifecycle-avatar.png'));
    assert.ok(detail.includes('id="post-start"'));
    assert.ok(detail.includes('href="#post-'+outlineId+'-section-1"'));
    assert.ok(detail.includes('href="#post-'+outlineId+'-section-2"'));
    assert.ok(!detail.includes('href="#post-'+outlineId+'-section-3"'));
    assert.ok(detail.includes('id="post-'+outlineId+'-section-3"'));
    const embedded=await (await fetch(base+'/mypage?tab=posts&post='+outlineId+'&category='+catB,{headers:{cookie:ownerCookie}})).text();
    assert.ok(embedded.includes('id="post-start"'));
    const hiddenContent=outlineContent.replace('"toc":"shown"','"toc":"hidden"');
    const hidden=await call('/api/posts/'+outlineId,'PATCH',{title:'Outline hidden',content:hiddenContent,categoryId:catB,visibility:'PUBLIC',updatedAt:outlinePost.body.post.updatedAt});
    assert.equal(hidden.status,200);
    const hiddenPage=await (await fetch(base+'/posts/'+outlineId)).text();
    assert.ok(!hiddenPage.includes('aria-label="글 목차"'));
    const draftOutline=await call('/api/drafts','PUT',{key:outlineId,title:'Saved outline',content:hiddenContent,categoryId:catB,visibility:'PUBLIC',version:null});
    assert.equal(draftOutline.status,200);
    assert.equal(JSON.parse((await call('/api/drafts?key='+outlineId)).body.draft.content.slice(prefix.length)).attrs.toc,'hidden');
    await call('/api/posts/'+outlineId,'DELETE');

    // Engagement checks run against the isolated database, never existing posts.
    const engagementUrl = '/api/posts/' + post.id;
    const privateUrl = '/api/posts/' + shared.body.post.id;
    assert.equal((await call(privateUrl+'/engagement','GET',undefined,otherCookie)).status,404);
    assert.equal((await call(privateUrl+'/likes','PUT',{},otherCookie)).status,404);
    assert.equal((await call(privateUrl+'/comments','POST',{content:'No access',nickname:'Guest',password:'secret'},null)).status,404);
    assert.equal((await call(privateUrl+'/views','POST',{},null)).status,404);
    assert.equal((await call(engagementUrl+'/likes','PUT',{},null)).status,401);
    assert.equal((await call(engagementUrl+'/likes','PUT',{},otherCookie)).status,200);
    assert.equal((await call(engagementUrl+'/likes','PUT',{},otherCookie)).body.likes,1,'likes are idempotent');
    let stats=(await call(engagementUrl+'/engagement','GET',undefined,otherCookie)).body;
    assert.equal(stats.liked,true); assert.equal(stats.likes,1);
    let likedPage=await (await fetch(base+'/mypage?tab=likes',{headers:{cookie:otherCookie}})).text();
    assert.ok(likedPage.includes('Public lifecycle post'));
    assert.ok(likedPage.includes('내가 좋아요 한 글'));
    await db.query('INSERT INTO "PostLike" ("postId","userId") VALUES ($1,$2)',[shared.body.post.id,other]);
    likedPage=await (await fetch(base+'/mypage?tab=likes',{headers:{cookie:otherCookie}})).text();
    assert.ok(!likedPage.includes('Shared image'),'likes list must not leak inaccessible posts');
    assert.equal((await call(engagementUrl+'/likes','DELETE',{},otherCookie)).body.likes,0);
    likedPage=await (await fetch(base+'/mypage?tab=likes',{headers:{cookie:otherCookie}})).text();
    assert.ok(!likedPage.includes('Public lifecycle post'));

    let created=await call(engagementUrl+'/comments','POST',{content:'<script>not executable</script>',anonymous:true,nickname:'익명 독자',password:'comment-secret',authorId:owner},null);
    assert.equal(created.status,201,JSON.stringify(created));
    const anonId=created.body.comment.id;
    let inbox = (await call('/api/notifications')).body;
    assert.equal(inbox.comments.length,1,'anonymous comments notify the post owner');
    assert.equal(inbox.comments[0].comment.id,anonId);
    assert.ok(!JSON.stringify(inbox).includes('passwordHash'));
    const noticeId = inbox.comments[0].id;
    assert.equal((await call('/api/notifications','GET',undefined,otherCookie)).body.comments.length,0);
    await call('/api/notifications','DELETE',{id:noticeId},otherCookie);
    assert.equal((await call('/api/notifications')).body.comments.length,1,'another user cannot delete notifications');
    await call('/api/notifications','DELETE',{id:noticeId});
    assert.equal((await call('/api/notifications')).body.comments.length,0);

    const storedComment=(await db.query('SELECT * FROM "Comment" WHERE id=$1',[anonId])).rows[0];
    assert.equal(storedComment.authorId,null,'guest comment has no account link');
    assert.notEqual(storedComment.passwordHash,'comment-secret');
    stats=(await call(engagementUrl+'/engagement','GET',undefined,null)).body;
    const anon=stats.comments.find(item=>item.id===anonId);
    assert.equal(anon.image,null); assert.equal(anon.authorId,null); assert.equal(anon.anonymous,true);
    assert.ok(!JSON.stringify(stats).includes('passwordHash'));
    assert.ok(!JSON.stringify(stats).includes('comment-secret'));
    assert.equal((await call(engagementUrl+'/comments/'+anonId,'PATCH',{content:'Wrong password',password:'wrong'},null)).status,403);
    assert.equal((await call(engagementUrl+'/comments/'+anonId,'PATCH',{content:'Edited anonymously',password:'comment-secret'},null)).status,200);
    assert.equal((await call(engagementUrl+'/comments/'+anonId,'DELETE',{password:'wrong'},null)).status,403);
    assert.equal((await call(engagementUrl+'/comments/'+anonId,'DELETE',{password:'comment-secret'},null)).status,200);
    created=await call(engagementUrl+'/comments','POST',{content:'Account comment',anonymous:true,nickname:'Spoofed nickname',authorId:other},ownerCookie);
    assert.equal(created.status,201); const memberId=created.body.comment.id;
    assert.equal((await call('/api/notifications')).body.comments.length,0,'own comments do not notify');
    const readerComment = await call(engagementUrl+'/comments','POST',{content:'Reader notification'},otherCookie);
    assert.equal(readerComment.status,201);
    inbox = (await call('/api/notifications')).body;
    assert.equal(inbox.comments.length,1,'account comments notify the owner');
    await call('/api/notifications','DELETE',{all:true});
    assert.equal((await call('/api/notifications')).body.comments.length,0);
    assert.equal((await db.query('SELECT id FROM "Comment" WHERE id=$1',[readerComment.body.comment.id])).rowCount,1,'notification deletion preserves comment');
    await call(engagementUrl+'/comments/'+readerComment.body.comment.id,'DELETE',{},otherCookie);

    stats=(await call(engagementUrl+'/engagement','GET',undefined,null)).body;
    const member=stats.comments.find(item=>item.id===memberId);
    assert.equal(member.authorId,owner); assert.equal(member.anonymous,false,'signed-in users cannot request anonymous authorship'); assert.equal(member.image,'https://example.com/lifecycle-avatar.png'); assert.notEqual(member.nickname,'Spoofed nickname');
    assert.equal((await call(engagementUrl+'/comments/'+memberId,'PATCH',{content:'Not mine'},otherCookie)).status,403);
    assert.equal((await call(engagementUrl+'/comments/'+memberId,'DELETE',{},otherCookie)).status,403);
    assert.equal((await call(engagementUrl+'/comments/'+memberId,'PATCH',{content:'Updated by account'},ownerCookie)).status,200);
    created=await call(engagementUrl+'/comments','POST',{content:'Moderation test',nickname:'Guest',password:'secret'},null);
    assert.equal(created.status,201);
    assert.equal((await call(engagementUrl+'/comments/'+created.body.comment.id,'DELETE',{},ownerCookie)).status,200,'post owner can moderate anonymous comments');
    assert.equal((await call('/api/notifications')).body.comments.length,0,'deleted comments remove their notifications');
    assert.equal((await call(engagementUrl+'/comments','POST',{content:'x'.repeat(2001),nickname:'Guest',password:'secret'},null)).status,400);
    assert.equal((await call(engagementUrl+'/comments','POST',{content:'hello',nickname:'Guest',password:'짧'.repeat(25)},null)).status,400,'bcrypt byte length is bounded');
    for(let i=0;i<33;i++) await db.query('INSERT INTO "Comment" (id,"postId","authorId",nickname,content,"updatedAt") VALUES ($1,$2,$3,$4,$5,NOW())',[randomUUID(),post.id,owner,'Member','Pagination '+i]);
    stats=(await call(engagementUrl+'/engagement','GET',undefined,null)).body;
    assert.equal(stats.comments.length,30); assert.ok(stats.nextCursor);
    const more=(await call(engagementUrl+'/engagement?cursor='+stats.nextCursor,'GET',undefined,null)).body;
    assert.equal(more.comments.length,4); assert.equal(more.nextCursor,null);
    assert.ok(!more.comments.some(item=>stats.comments.some(previous=>previous.id===item.id)));
    const chronologicalComments = (await db.query('SELECT id FROM "Comment" WHERE "postId"=$1 ORDER BY "createdAt" ASC, id ASC',[post.id])).rows.map(item=>item.id);
    assert.deepEqual([...stats.comments,...more.comments].map(item=>item.id),chronologicalComments,'comments stay oldest-first across page boundaries');


    assert.equal((await call(engagementUrl+'/views','POST',{},ownerCookie)).body.views,0,'author views excluded');
    assert.equal((await call(engagementUrl+'/views','POST',{},otherCookie)).body.views,1);
    assert.equal((await call(engagementUrl+'/views','POST',{},otherCookie)).body.views,1,'same reader/day deduplicated');
    let viewResponse=await fetch(base+engagementUrl+'/views',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});
    assert.equal(viewResponse.status,200);
    const visitorCookie=viewResponse.headers.get('set-cookie').split(';')[0];
    assert.match(visitorCookie,/blog-visitor=/);
    assert.equal((await viewResponse.json()).views,2);
    assert.equal((await call(engagementUrl+'/views','POST',{},visitorCookie)).body.views,2);
    await db.query('INSERT INTO "PostView" ("postId","viewerHash",day,"createdAt") VALUES ($1,$2,$3,NOW()-INTERVAL \'8 days\')',[post.id,'old-reader','2000-01-01']);
    await db.query('INSERT INTO "PostView" ("postId","viewerHash",day) VALUES ($1,$2,$3)',[shared.body.post.id,'private-reader','2000-01-01']);
    const home=await (await fetch(base)).text();
    assert.ok(home.includes('많이 읽은 글'));
    assert.ok(home.includes('인기 글 조회 기간'));
    const ranking=home.slice(home.indexOf('<section class="weekly-popular"'),home.indexOf('</ol>',home.indexOf('<section class="weekly-popular"')));
    assert.ok(ranking.includes('Public lifecycle post'));
    assert.ok(/조회 (?:<!-- -->)?2/.test(ranking),'weekly count excludes eight day old views');
    assert.ok(!ranking.includes('Shared image'));
    assert.ok(!home.includes('전체 글 읽기'));
    const csrf=await fetch(base+engagementUrl+'/likes',{method:'PUT',headers:{cookie:otherCookie,'Content-Type':'application/json',origin:'https://untrusted.example'},body:'{}'});
    assert.equal(csrf.status,403);

    const formatted=prefix+JSON.stringify({type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Formatted content',marks:[{type:'textStyle',attrs:{fontSize:'24px'}},{type:'highlight',attrs:{color:'#bbf7d0'}}]}]}]});
    let tagDraft=await call('/api/drafts','PUT',{key:'new',title:'Tagged draft',content:formatted,tags:['React','개발'],categoryId:catA,visibility:'PUBLIC',version:null});
    assert.equal(tagDraft.status,200); assert.deepEqual(tagDraft.body.draft.tags,['React','개발']);
    const tagged=await call('/api/posts','POST',{title:'Tagged post',content:formatted,tags:['React','개발','React'],categoryId:catA,visibility:'PUBLIC',draftVersion:tagDraft.body.draft.version});
    assert.equal(tagged.status,201); assert.deepEqual(tagged.body.post.tags,['React','개발']);
    const formattedPage=await (await fetch(base+'/posts/'+tagged.body.post.id)).text();
    assert.ok(formattedPage.includes('font-size:24px')); assert.ok(formattedPage.includes('background-color:#bbf7d0')); assert.ok(formattedPage.includes('개발'));
    const tagEdit=await call('/api/posts/'+tagged.body.post.id,'PATCH',{title:'Tags changed',content:formatted,tags:['수정'],categoryId:catA,visibility:'PUBLIC',updatedAt:tagged.body.post.updatedAt});
    assert.equal(tagEdit.status,200); assert.deepEqual(tagEdit.body.post.tags,['수정']);
    assert.equal((await call('/api/posts','POST',{title:'Bad tags',content:formatted,tags:['x'.repeat(25)],categoryId:catA,visibility:'PUBLIC'})).status,400);
    await call('/api/posts/'+tagged.body.post.id,'DELETE');
    const signupEmail='signup-'+randomUUID()+'@example.test';
    const signupToken=randomUUID();
    await db.query('INSERT INTO "VerificationToken" (identifier,token,expires) VALUES ($1,$2,NOW()+INTERVAL \'1 hour\')',[JSON.stringify({name:'가입 이름',nickname:'가입 닉네임',email:signupEmail,passwordHash:'fixture'}),signupToken]);
    assert.equal((await fetch(base+'/verify-email?token='+signupToken)).status,200);
    const signedUp=(await db.query('SELECT name,nickname,tag FROM "User" WHERE email=$1',[signupEmail])).rows[0];
    assert.equal(signedUp.name,'가입 이름'); assert.equal(signedUp.nickname,'가입 닉네임'); assert.match(signedUp.tag,/^\d{4}$/);
    await db.query('DELETE FROM "User" WHERE email=$1',[signupEmail]);
    const originalDate=post.createdAt;
    edited=await call('/api/posts/'+post.id,'PATCH',{title:'Without image',content:content(null),categoryId:catB,visibility:'PUBLIC',updatedAt:post.updatedAt});
    assert.equal(edited.status,200);post=edited.body.post;assert.equal(post.createdAt,originalDate);
    assert.equal((await db.query('SELECT "orphanedAt" FROM "ImageAsset" WHERE name=$1',[name])).rows[0].orphanedAt,null,'another post keeps shared image');
    assert.equal((await call('/api/posts/'+shared.body.post.id,'DELETE')).status,200);
    assert.ok((await db.query('SELECT "orphanedAt" FROM "ImageAsset" WHERE name=$1',[name])).rows[0].orphanedAt);
    await cleanup();assert.equal((await fetch(base+image,{headers:{cookie:ownerCookie}})).status,200,'24h undo grace');
    // Undo: a new server draft reattaches the removed image and prevents deletion.
    draft=await call('/api/drafts','PUT',{key:post.id,title:post.title,content:content(image),categoryId:catB,visibility:'PUBLIC',version:null});
    assert.equal(draft.status,200);version=draft.body.draft.version;
    assert.equal((await db.query('SELECT "orphanedAt" FROM "ImageAsset" WHERE name=$1',[name])).rows[0].orphanedAt,null);
    const discarded=await call('/api/drafts','DELETE',{key:post.id,version}); assert.equal(discarded.status,200,JSON.stringify(discarded));
    await db.query('UPDATE "ImageAsset" SET "orphanedAt"=NOW()-INTERVAL \'25 hours\' WHERE name=$1',[name]);
    const cleaned=await cleanup();assert.equal(cleaned.deleted,1);assert.equal((await fetch(base+image,{headers:{cookie:ownerCookie}})).status,404);
    assert.equal((await db.query('SELECT name FROM "ImageAsset" WHERE name=$1',[name])).rowCount,0);
    assert.equal((await call('/api/posts/'+post.id,'DELETE',undefined,otherCookie)).status,404);
    assert.equal((await call('/api/posts/'+post.id,'DELETE')).status,200);
    assert.equal((await fetch(base+'/posts/'+post.id)).status,404);
    assert.equal((await db.query('SELECT id FROM "Comment" WHERE "postId"=$1',[post.id])).rowCount,0);
    assert.equal((await db.query('SELECT "postId" FROM "PostView" WHERE "postId"=$1',[post.id])).rowCount,0);
    assert.equal((await fetch(base+'/api/maintenance/images',{method:'POST'})).status,401);
    console.log('PASS: drafts, posts, media lifecycle, permissions, formatting, tags, anonymous/account comments, likes, weekly views and signup names');
  } catch (error) {
    console.error(log);
    throw error;
  } finally {
    server.kill();
    if(server.exitCode===null) await Promise.race([once(server,'exit'),new Promise(resolve=>setTimeout(resolve,3000))]);
    await db.query('DELETE FROM "User" WHERE id=ANY($1::text[])',[[owner,other,friend]]);
    await db.end();
    await admin.query('DROP DATABASE "' + databaseName + '" WITH (FORCE)');
    await admin.end();
    for (const name of await readdir(directory)) await unlink(path.join(directory,name));
    await rmdir(directory);
  }
});
